# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: APX Docs
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  APX Documentation Project

baseurl: "/apx" # the subpath of your site, e.g. /blog
url: "https://cogu.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: cogu

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - slask/
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - .gitignore
  - .markdownlint.json

kramdown:
  toc_levels: "1..2"

